#!/bin/bash
# Findsploit 20131223 by 1N3, 20180124 rewritten by termilus.

# Findsploit is a simple bash script to quickly and easily search both local and online exploit databases. Currently searches Metasploit, Exploit-DB, SecurityFocus, 0day.today, NVD, CVEs, and Google.

# REQUIREMENTS
# This script relies on exploitdb's searchsploit script

# INSTALLATION
# 1. git clone https://github.com/cjdupreez/findsploit.git /opt/
# 2. ln -s /opt/findsploit/findsploit /usr/bin/findsploit
# 3. chmod +rx /usr/bin/findsploit
# 4. To run, type findsploit <name of product> <version> <local or remote>


clear

VAR1=$1;
VAR2=$2;
VAR3=$3;

if [ -z "$1" ];
then
        echo "[+] findsploit by nonXero rewritten by termilus"
	echo "[+] Usage: findsploit <name of product> <version> <local or remote>"
        echo "[+] Example: findsploit freeFTPd 1.0 remote"
        exit;
else
        echo "[+] findsploit by nonXero rewritten by termilus"
        echo ""
        echo "[+] Metasploit exploits"
        echo ""
        egrep -i "$VAR1" /usr/share/metasploit-framework/modules/exploits/* -R | grep "Name"
        echo ""
        echo "[+] ExploitDB exploits"
        echo ""
        /usr/bin/searchsploit $VAR1 $VAR2 $VAR3
        echo ""
        echo "[+] Press any key to search online or Ctrl+C to exit..."
        echo ""
	read test

        echo "[+] Search Security Focus for exploits"
	echo ""
	firefox 'https://www.google.com/search?q='$VAR1'+'$VAR2'+'$VAR3'+exploit+site:www.securityfocus.com' 2> /dev/null

        echo "[+] Search 0day.today for exploits"
	echo ""
	firefox 'https://www.google.com/search?q='$VAR1'+'$VAR2'+'$VAR3'+site:0day.today' 2> /dev/null

        echo "[+] Search PacketStorm for exploits"
        echo ""
	firefox 'https://packetstormsecurity.com/search/?q='$VAR1'+'$VAR2'+'$VAR3 2> /dev/null

	echo "[+] Search NVD for exploits"
	echo ""
	firefox 'https://nvd.nist.gov/vuln/search/results?adv_search=false&form_type=basic&results_type=overview&search_type=all&query='$VAR1 2> /dev/null

	echo "[+] Search CVE details for exploits"
        echo ""
	firefox 'http://www.cvedetails.com/product-search.php?vendor_id=0&search='$VAR1 2> /dev/null

	echo "[+] Search Google for exploits"
        echo ""
	firefox 'https://www.google.com/search?q='$VAR1'+'$VAR2'+'$VAR3'+-site%3Anvd.nist.gov+-site%3A0day.today+-site%3Awww.securityfocus.com+-site%3Awww.cvedetails.com+-site%3Awww.exploit-db.com+-site%3Awww.packetstormsecurity.com+exploit' 2>/dev/null
fi

exit
